const ENTRY_TYPE = "type/ENTRY";
const INPUT_TYPE = "type/INPUT";
const OUTPUT_TYPE = "type/OUTPUT";
const MOVEMENT_TYPE = "type/MOVEMENT";
const CONDITION_TYPE = "type/CONDITION";
const ASSIGNMENT_TYPE = "type/ASSIGNMENT";
const UNRECOGNIZED_TYPE = "type/UNRECOGNIZED";

module.exports = {
  ENTRY_TYPE,
  INPUT_TYPE,
  OUTPUT_TYPE,
  MOVEMENT_TYPE,
  CONDITION_TYPE,
  ASSIGNMENT_TYPE,
  UNRECOGNIZED_TYPE
};
